terraform {
  required_version = ">= 1.7, < 2.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.61"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }

  # Partial backend: keep the bucket/key/lock-table OUT of code so this stack can be
  # init'd against the shared remote state without committing environment specifics.
  # Supply them at init time with -backend-config (see README.md):
  #   terraform init \
  #     -backend-config="bucket=${TFSTATE_BUCKET}" \
  #     -backend-config="key=eks/terraform.tfstate" \
  #     -backend-config="dynamodb_table=ssa-tf-locks" \
  #     -backend-config="region=us-east-1" \
  #     -backend-config="encrypt=true"
  # encrypt=true is set explicitly because this state contains a secret: the RDS
  # master password (generated by Terraform, also stored in Secrets Manager).
  backend "s3" {}
}
